import json

SAMPLE_JOBS = [
    {
        "title": "Data Scientist",
        "company": "Johnson & Johnson",
        "location": "Mumbai, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Data%20Scientist%20Johnson%20%26%20Johnson",
        "description": """We are looking for a Data Scientist to develop ML models for clinical trial data analysis. You will work with large datasets, build predictive models, and collaborate with clinical teams to extract insights from patient data. Skills: Python, Scikit-learn, Pandas, SQL, Statistical Analysis, Feature Engineering, A/B Testing. Experience with healthcare data and NLP is a plus.""",
        "required_skills": ["python", "scikit-learn", "pandas", "sql", "statistical analysis",
                            "feature engineering", "machine learning", "nlp", "healthcare"],
        "industry": "healthcare",
    },
    {
        "title": "Senior Data Scientist",
        "company": "IQVIA",
        "location": "Mumbai, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Data%20Scientist%20IQVIA",
        "description": """Lead data science initiatives for clinical trial optimization. Build predictive models for patient recruitment and retention, analyze real-world evidence, and collaborate with cross-functional teams. Expertise in Python, R, ML, and healthcare data standards required.""",
        "required_skills": ["python", "r", "machine learning", "sql", "pandas",
                            "statistical analysis", "healthcare", "feature engineering",
                            "data visualization", "leadership"],
        "industry": "healthcare",
    },
    {
        "title": "Full Stack Developer",
        "company": "Microsoft",
        "location": "Hyderabad, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Full%20Stack%20Developer%20Microsoft%20Hyderabad",
        "description": """Build and maintain cloud-native web applications using React, TypeScript, and .NET Core. Design RESTful APIs, optimize database queries, and collaborate with product teams in an agile environment. Experience with Azure, CI/CD, and microservices preferred.""",
        "required_skills": ["react", "typescript", "c#", "asp.net", "azure", "sql",
                            "rest api", "git", "ci/cd", "agile", "microservices"],
        "industry": "saas",
    },
    {
        "title": "Frontend Engineer",
        "company": "Netflix",
        "location": "Bengaluru, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Frontend%20Engineer%20Netflix",
        "description": """Build high-performance UI components for streaming platforms. Optimize rendering, implement A/B testing frameworks, and ensure cross-browser compatibility. Deep expertise in React, TypeScript, and performance profiling required.""",
        "required_skills": ["react", "typescript", "javascript", "html", "css",
                            "performance optimization", "a/b testing", "git", "webpack"],
        "industry": "media",
    },
    {
        "title": "ML Engineer — NLP",
        "company": "Google",
        "location": "Bengaluru, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=ML%20Engineer%20NLP%20Google%20Bengaluru",
        "description": """Build and deploy NLP models at scale. Design RAG pipelines, fine-tune LLMs, and work with Gemini models on Vertex AI. Strong Python, PyTorch/JAX, and experience with transformers required. Knowledge of LangChain, vector databases, and MLOps preferred.""",
        "required_skills": ["python", "nlp", "pytorch", "transformers", "langchain",
                            "rag", "vertex ai", "gcp", "docker", "fine-tuning", "llm"],
        "industry": "saas",
    },
    {
        "title": "AI Engineer — Agentic Systems",
        "company": "Pharmaceutical Company",
        "location": "Remote, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=AI%20Engineer%20Agentic%20Systems%20Pharma",
        "description": """Design and build multi-agent AI systems for clinical reporting automation. Use LangGraph, Google ADK, and Vertex AI to orchestrate document processing, LLM-based generation, and validation workflows. Strong Python, FastAPI, and GCP experience required. Familiarity with clinical data standards is a plus.""",
        "required_skills": ["python", "langgraph", "langchain", "google adk", "vertex ai",
                            "gcp", "fastapi", "docker", "llm", "multi-agent", "document processing",
                            "rag", "clinical"],
        "industry": "healthcare",
    },
    {
        "title": "Data Analyst",
        "company": "Flipkart",
        "location": "Bengaluru, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Data%20Analyst%20Flipkart%20Bengaluru",
        "description": """Analyze e-commerce data to drive business decisions. Build dashboards, run A/B tests, and provide actionable insights to product teams. Proficiency in SQL, Python, and visualization tools (Tableau/Plotly) required. Experience with large-scale consumer data preferred.""",
        "required_skills": ["python", "sql", "data analysis", "data visualization",
                            "a/b testing", "pandas", "plotly", "statistical analysis"],
        "industry": "ecommerce",
    },
    {
        "title": "Machine Learning Engineer",
        "company": "Swiggy",
        "location": "Bengaluru, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Machine%20Learning%20Engineer%20Swiggy",
        "description": """Develop recommendation systems and forecasting models for food delivery logistics. Work with Python, Scikit-learn, XGBoost, and deploy on AWS/GCP. Experience with feature stores, model monitoring, and CI/CD pipelines for ML required.""",
        "required_skills": ["python", "scikit-learn", "xgboost", "machine learning",
                            "aws", "gcp", "docker", "ci/cd", "feature engineering",
                            "recommendation system", "forecasting"],
        "industry": "ecommerce",
    },
    {
        "title": "NLP Data Scientist",
        "company": "IQVIA",
        "location": "Remote, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=NLP%20Data%20Scientist%20IQVIA",
        "description": """Apply NLP to clinical and pharmaceutical text data. Build document classification, entity extraction, and summarization systems. Strong Python, HuggingFace, and experience with medical text data required. Knowledge of clinical trial data standards is a plus.""",
        "required_skills": ["python", "nlp", "huggingface", "transformers",
                            "entity extraction", "text classification", "healthcare",
                            "clinical", "pandas", "numpy"],
        "industry": "healthcare",
    },
    {
        "title": "Data Scientist — Computer Vision",
        "company": "Mahindra & Mahindra",
        "location": "Chennai, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Computer%20Vision%20Data%20Scientist%20Mahindra",
        "description": """Develop CV models for quality inspection and autonomous systems. Deep learning experience (PyTorch/TensorFlow) and deployment on edge devices required. Knowledge of MLOps and Docker preferred.""",
        "required_skills": ["python", "computer vision", "deep learning", "pytorch",
                            "tensorflow", "docker", "mlops"],
        "industry": "saas",
    },
    {
        "title": "Senior Data Scientist",
        "company": "American Express",
        "location": "Gurugram, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Senior%20Data%20Scientist%20American%20Express",
        "description": """Build ML models for fraud detection and risk scoring. Work with large-scale transaction data, feature engineering, and model deployment. Python, Scikit-learn, XGBoost, and SQL expertise required. Knowledge of graph databases and real-time inference is a plus.""",
        "required_skills": ["python", "scikit-learn", "xgboost", "sql", "feature engineering",
                            "machine learning", "fraud detection", "risk modeling",
                            "statistical analysis"],
        "industry": "fintech",
    },
    {
        "title": "Generative AI Engineer",
        "company": "Microsoft",
        "location": "Hyderabad, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Generative%20AI%20Engineer%20Microsoft%20Hyderabad",
        "description": """Build generative AI solutions using LLMs, RAG, and agentic frameworks. Develop on Azure AI, work with Prompt Flow, and integrate with enterprise data sources. Strong Python, LangChain, and experience deploying AI solutions at scale required.""",
        "required_skills": ["python", "langchain", "rag", "llm", "prompt engineering",
                            "azure", "docker", "generative ai", "agent"],
        "industry": "saas",
    },
    {
        "title": "Data Science Consultant",
        "company": "Deloitte",
        "location": "Mumbai, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Data%20Science%20Consultant%20Deloitte%20Mumbai",
        "description": """Lead data science engagements for clients across industries. Design ML solutions, build PoCs, and guide production deployment. Strong Python, cloud experience, and client-facing communication skills required. Consulting background preferred.""",
        "required_skills": ["python", "machine learning", "cloud", "gcp", "aws",
                            "communication", "stakeholder", "consulting",
                            "data analysis", "sql"],
        "industry": "consulting",
    },
    {
        "title": "Data Scientist — Recommendation Systems",
        "company": "Netflix",
        "location": "Remote, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Recommendation%20Systems%20Data%20Scientist",
        "description": """Design and optimize personalization algorithms serving millions of users. Deep expertise in collaborative filtering, matrix factorization, and deep learning for recommendations. Python, PyTorch, and large-scale distributed systems experience required.""",
        "required_skills": ["python", "pytorch", "recommendation system", "machine learning",
                            "deep learning", "collaborative filtering", "feature engineering",
                            "model evaluation", "a/b testing"],
        "industry": "saas",
    },
    {
        "title": "Junior Data Scientist",
        "company": "Zomato",
        "location": "Gurugram, India",
        "source": "Naukri.com",
        "url": "https://www.naukri.com/junior-data-scientist-jobs?k=junior%20data%20scientist",
        "description": """Entry-level data scientist role working on restaurant analytics, customer segmentation, and delivery optimization. Python, SQL, and basic ML knowledge required. Good learning opportunity with mentorship provided.""",
        "required_skills": ["python", "sql", "machine learning", "data analysis",
                            "pandas", "numpy", "scikit-learn", "communication"],
        "industry": "ecommerce",
    },
    {
        "title": "MLOps Engineer",
        "company": "Razorpay",
        "location": "Bengaluru, India",
        "source": "Indeed",
        "url": "https://www.indeed.co.in/jobs?q=MLOps+Engineer&l=Bengaluru",
        "description": """Build and maintain ML infrastructure, CI/CD pipelines for ML models, model monitoring, and feature stores. Docker, Kubernetes, Terraform, and cloud experience (GCP/AWS) required. Python and basic ML knowledge needed.""",
        "required_skills": ["python", "docker", "kubernetes", "terraform", "gcp",
                            "aws", "ci/cd", "mlops", "model monitoring"],
        "industry": "fintech",
    },
    {
        "title": "AI Research Scientist",
        "company": "Microsoft Research",
        "location": "Bengaluru, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=AI%20Research%20Scientist%20Microsoft%20Research",
        "description": """Conduct applied research in LLMs, multi-agent systems, and AI safety. Publish papers and transfer technology to products. PhD/MS preferred but strong publication record and open-source contributions considered. PyTorch, deep learning, and strong mathematical background required.""",
        "required_skills": ["python", "pytorch", "deep learning", "llm", "nlp",
                            "research", "multi-agent", "transformers", "huggingface"],
        "industry": "saas",
    },
    {
        "title": "Data Scientist — Healthcare Analytics",
        "company": "Apollo Hospitals",
        "location": "Hyderabad, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Healthcare%20Analytics%20Data%20Scientist%20Apollo",
        "description": """Apply data science to improve patient outcomes. Analyze electronic health records, build predictive models for disease progression, and create dashboards for clinical teams. Python, SQL, and healthcare data experience required. Knowledge of HIPAA and clinical data standards preferred.""",
        "required_skills": ["python", "sql", "healthcare", "machine learning",
                            "data analysis", "pandas", "statistical analysis",
                            "predictive modeling", "clinical"],
        "industry": "healthcare",
    },
    {
        "title": "Machine Learning Engineer — Document AI",
        "company": "Adobe",
        "location": "Noida, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Document%20AI%20Machine%20Learning%20Engineer%20Adobe",
        "description": """Build ML models for document understanding — layout analysis, table extraction, and form parsing. Deep learning, OCR, and NLP experience needed. Python, PyTorch, and deployment experience required.""",
        "required_skills": ["python", "pytorch", "deep learning", "nlp", "ocr",
                            "document processing", "computer vision", "docker",
                            "huggingface", "transformers"],
        "industry": "saas",
    },
    {
        "title": "Data Scientist — Supply Chain",
        "company": "Tata Consultancy Services",
        "location": "Pune, India",
        "source": "Naukri.com",
        "url": "https://www.naukri.com/data-scientist-jobs?k=supply%20chain%20data%20scientist",
        "description": """Build forecasting and optimization models for supply chain operations. Work with demand prediction, inventory optimization, and logistics routing. Python, SQL, and time series analysis expertise required.""",
        "required_skills": ["python", "sql", "time series", "forecasting",
                            "machine learning", "optimization", "data analysis",
                            "pandas", "scikit-learn"],
        "industry": "consulting",
    },
    {
        "title": "Data Analyst — Marketing Analytics",
        "company": "Unilever",
        "location": "Mumbai, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Marketing%20Analytics%20Data%20Analyst%20Unilever",
        "description": """Analyze marketing campaign performance, customer segmentation, and ROI. Build dashboards and present insights to marketing leadership. Strong SQL, Python, and data visualization skills required. Experience with A/B testing and attribution modeling preferred.""",
        "required_skills": ["python", "sql", "data analysis", "data visualization",
                            "a/b testing", "pandas", "plotly", "statistical analysis",
                            "communication"],
        "industry": "consulting",
    },
    {
        "title": "NLP Engineer",
        "company": "Samsung Research",
        "location": "Bengaluru, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=NLP%20Engineer%20Samsung%20Research%20Bengaluru",
        "description": """Develop state-of-the-art NLP models for multilingual understanding, dialogue systems, and text generation. PyTorch, HuggingFace, and transformer architecture expertise required. Experience with model compression and on-device deployment is a plus.""",
        "required_skills": ["python", "nlp", "pytorch", "huggingface", "transformers",
                            "deep learning", "llm", "fine-tuning", "model evaluation"],
        "industry": "saas",
    },
    {
        "title": "Data Scientist — Credit Risk",
        "company": "HDFC Bank",
        "location": "Mumbai, India",
        "source": "LinkedIn",
        "url": "https://www.linkedin.com/jobs/search/?keywords=Credit%20Risk%20Data%20Scientist%20HDFC%20Bank",
        "description": """Develop credit risk models using ML. Work with large financial datasets, build scorecards, and ensure regulatory compliance. Python, SQL, and statistical modeling expertise required. Banking/risk domain knowledge preferred.""",
        "required_skills": ["python", "sql", "machine learning", "statistical modeling",
                            "risk modeling", "feature engineering", "model evaluation",
                            "logistic regression", "xgboost", "pandas"],
        "industry": "fintech",
    },
    # Glassdoor
    {
        "title": "Senior Data Scientist",
        "company": "Spotify",
        "location": "Bengaluru, India",
        "source": "Glassdoor",
        "url": "https://www.glassdoor.co.in/Job/jobs.htm?sc.keyword=Senior%20Data%20Scientist%20Bengaluru",
        "description": """Drive experimentation and personalization at Spotify scale. Analyze user behavior, design A/B tests, and build ML models to enhance music recommendations. Strong Python, SQL, and statistical thinking required.""",
        "required_skills": ["python", "sql", "machine learning", "a/b testing", "recommendation system",
                            "statistical analysis", "data analysis", "pandas", "communication"],
        "industry": "saas",
    },
    {
        "title": "AI/ML Engineer",
        "company": "Intel",
        "location": "Bengaluru, India",
        "source": "Glassdoor",
        "url": "https://www.glassdoor.co.in/Job/jobs.htm?sc.keyword=AI%20ML%20Engineer%20Intel%20Bengaluru",
        "description": """Develop and optimize ML models for edge AI and computer vision applications. Work with OpenVINO, PyTorch, and deploy on Intel hardware. Strong C++/Python skills and model optimization experience required.""",
        "required_skills": ["python", "pytorch", "computer vision", "deep learning", "docker",
                            "model optimization", "tensorflow", "c++"],
        "industry": "saas",
    },
    # Wellfound (AngelList)
    {
        "title": "Data Scientist — Early-Stage",
        "company": "Razorpay (via Wellfound)",
        "location": "Bengaluru, India",
        "source": "Wellfound",
        "url": "https://wellfound.com/search/jobs?q=Data+Scientist+Bengaluru",
        "description": """Join a fast-growing fintech startup as the first data scientist. Build fraud detection models, customer analytics dashboards, and help shape data culture. Python, SQL, and strong product sense required.""",
        "required_skills": ["python", "sql", "machine learning", "data analysis", "fraud detection",
                            "pandas", "feature engineering", "communication"],
        "industry": "fintech",
    },
    {
        "title": "ML Engineer — GenAI Startup",
        "company": "Krutrim (via Wellfound)",
        "location": "Bengaluru, India",
        "source": "Wellfound",
        "url": "https://wellfound.com/search/jobs?q=ML+Engineer+Generative+AI+Bengaluru",
        "description": """Build generative AI products for Indian languages. Fine-tune LLMs, build RAG pipelines, and deploy at scale. Strong Python, PyTorch, and NLP background required. Startup experience preferred.""",
        "required_skills": ["python", "pytorch", "nlp", "llm", "rag", "langchain", "fine-tuning",
                            "transformers", "huggingface", "docker"],
        "industry": "saas",
    },
    # ZipRecruiter
    {
        "title": "Data Analyst — Product Analytics",
        "company": "Myntra",
        "location": "Bengaluru, India",
        "source": "ZipRecruiter",
        "url": "https://www.ziprecruiter.com/candidate/search?search=Data%20Analyst%20Myntra%20Bengaluru",
        "description": """Analyze product usage and customer behavior to drive feature improvements. Build funnels, cohort analyses, and dashboards. Strong SQL, Python, and product analytics experience required. Knowledge of e-commerce metrics preferred.""",
        "required_skills": ["python", "sql", "data analysis", "a/b testing", "pandas",
                            "data visualization", "statistical analysis", "communication"],
        "industry": "ecommerce",
    },
    {
        "title": "Machine Learning Engineer",
        "company": "Uber",
        "location": "Bengaluru, India",
        "source": "ZipRecruiter",
        "url": "https://www.ziprecruiter.com/candidate/search?search=Machine%20Learning%20Engineer%20Uber%20Bengaluru",
        "description": """Build ML models for pricing, ETA prediction, and marketplace optimization. Work with petabyte-scale data. Strong Python, distributed ML, and production deployment experience required. Knowledge of Go is a plus.""",
        "required_skills": ["python", "machine learning", "deep learning", "feature engineering",
                            "pytorch", "gcp", "docker", "model deployment"],
        "industry": "saas",
    },
    # Google Jobs
    {
        "title": "Data Scientist — Search Quality",
        "company": "Google",
        "location": "Hyderabad, India",
        "source": "Google Jobs",
        "url": "https://www.google.com/search?q=Data+Scientist+Google+Hyderabad+2025&ibp=htl;jobs",
        "description": """Improve Google Search quality through data analysis and ML. Design metrics, run experiments, and build models to enhance search relevance. Strong Python, SQL, and experimental design skills required.""",
        "required_skills": ["python", "sql", "machine learning", "a/b testing", "statistical analysis",
                            "data analysis", "feature engineering", "communication"],
        "industry": "saas",
    },
    {
        "title": "AI Research Engineer",
        "company": "DeepMind (Google)",
        "location": "Bengaluru, India",
        "source": "Google Jobs",
        "url": "https://www.google.com/search?q=AI+Research+Engineer+DeepMind+Bengaluru&ibp=htl;jobs",
        "description": """Conduct cutting-edge AI research and transfer breakthroughs to Google products. Work on LLMs, reinforcement learning, and multi-agent systems. PhD/MS preferred, strong publication record and PyTorch/JAX expertise required.""",
        "required_skills": ["python", "pytorch", "deep learning", "llm", "nlp", "research",
                            "transformers", "huggingface", "multi-agent", "reinforcement learning"],
        "industry": "saas",
    },
    # Monster
    {
        "title": "Data Scientist — NLP & Text Analytics",
        "company": "Accenture",
        "location": "Bengaluru, India",
        "source": "Monster",
        "url": "https://www.monsterindia.com/search/data-scientist-jobs?q=Data%20Scientist%20NLP",
        "description": """Apply NLP to analyze unstructured text data for client engagements. Build text classification, entity extraction, and sentiment analysis pipelines. Python, spaCy, and cloud deployment experience required.""",
        "required_skills": ["python", "nlp", "transformers", "huggingface", "machine learning",
                            "cloud", "docker", "entity extraction", "text classification"],
        "industry": "consulting",
    },
    {
        "title": "BI & Analytics Lead",
        "company": "Walmart",
        "location": "Bengaluru, India",
        "source": "Monster",
        "url": "https://www.monsterindia.com/search/data-scientist-jobs?q=BI%20Analytics%20Walmart",
        "description": """Lead analytics for Walmart's supply chain and retail operations. Build dashboards, forecast demand, and drive data-informed decisions. Strong SQL, Python, Tableau, and stakeholder management skills required.""",
        "required_skills": ["python", "sql", "data analysis", "data visualization", "forecasting",
                            "pandas", "communication", "stakeholder"],
        "industry": "ecommerce",
    },
    # === ADDED: Expanded job sources ===
    # TimesJobs
    {
        "title": "Data Scientist — Predictive Analytics",
        "company": "Tata Consultancy Services",
        "location": "Mumbai, India",
        "source": "TimesJobs",
        "url": "https://www.timesjobs.com/jobsearch?q=Data+Scientist+Predictive+Analytics",
        "description": """Build predictive models for enterprise clients across banking, retail, and telecom domains. End-to-end ML lifecycle from data exploration to model deployment. Python, Scikit-learn, and SQL required.""",
        "required_skills": ["python", "scikit-learn", "sql", "predictive modeling", "feature engineering",
                            "pandas", "model deployment", "statistical modeling"],
        "industry": "consulting",
    },
    {
        "title": "NLP Engineer — Document Intelligence",
        "company": "Infosys",
        "location": "Pune, India",
        "source": "TimesJobs",
        "url": "https://www.timesjobs.com/jobsearch?q=NLP+Engineer+Infosys",
        "description": """Develop NLP solutions for document processing, entity extraction, and intelligent search. Work with transformer models, OCR pipelines, and cloud deployment. Python, spaCy, HuggingFace experience required.""",
        "required_skills": ["python", "nlp", "huggingface", "transformers", "entity extraction",
                            "text classification", "docker", "gcp", "pandas"],
        "industry": "saas",
    },
    {
        "title": "AI Solutions Architect",
        "company": "Wipro",
        "location": "Bengaluru, India",
        "source": "TimesJobs",
        "url": "https://www.timesjobs.com/jobsearch?q=AI+Solutions+Architect+Wipro",
        "description": """Design end-to-end AI solutions for enterprise clients. Architect ML systems, select appropriate models, and guide implementation teams. Strong Python, cloud architecture, and client consulting skills required.""",
        "required_skills": ["python", "gcp", "aws", "docker", "machine learning",
                            "communication", "stakeholder", "consulting", "model deployment"],
        "industry": "consulting",
    },
    # AngelList / Wellfound (new)
    {
        "title": "Data Scientist — Early Stage",
        "company": "RazorpayX (Startup)",
        "location": "Bengaluru, India",
        "source": "Wellfound",
        "url": "https://wellfound.com/jobs?q=Data+Scientist+Startup+Bengaluru",
        "description": """Join as founding data scientist at a fintech startup. Build data infrastructure, design ML models for credit risk, and shape data culture from day one. Full ownership of ML stack. Python, SQL, and startup mindset required.""",
        "required_skills": ["python", "sql", "machine learning", "risk modeling",
                            "feature engineering", "pandas", "gcp"],
        "industry": "fintech",
    },
    {
        "title": "ML Engineer — EdTech",
        "company": "Unacademy (Startup)",
        "location": "Bengaluru, India",
        "source": "Wellfound",
        "url": "https://wellfound.com/jobs?q=ML+Engineer+EdTech+Bengaluru",
        "description": """Build personalized learning recommendation systems serving 50M+ students. Work on content recommendation, knowledge graph construction, and adaptive learning algorithms. PyTorch, NLP, and large-scale data processing experience required.""",
        "required_skills": ["python", "pytorch", "nlp", "recommendation system", "machine learning",
                            "deep learning", "feature engineering", "model evaluation"],
        "industry": "saas",
    },
    {
        "title": "Data Analyst — Product Analytics",
        "company": "Cred (Startup)",
        "location": "Bengaluru, India",
        "source": "Wellfound",
        "url": "https://wellfound.com/jobs?q=Data+Analyst+Product+Cred",
        "description": """Drive product decisions through data analysis and experimentation. Own A/B testing framework, build product dashboards, and deliver actionable insights. SQL, Python, and strong analytical thinking required.""",
        "required_skills": ["python", "sql", "data analysis", "a/b testing", "data visualization",
                            "pandas", "numpy", "communication"],
        "industry": "fintech",
    },
    # Dice
    {
        "title": "Senior ML Engineer — Computer Vision",
        "company": "Licious",
        "location": "Bengaluru, India",
        "source": "Dice",
        "url": "https://www.dice.com/jobs?q=Senior+ML+Engineer+Computer+Vision+India",
        "description": """Build computer vision models for quality inspection and inventory management. Deploy models to edge devices and manage the full ML lifecycle. PyTorch, OpenCV, and ONNX runtime experience required.""",
        "required_skills": ["python", "computer vision", "pytorch", "deep learning", "docker",
                            "model deployment", "model optimization"],
        "industry": "ecommerce",
    },
    {
        "title": "Data Engineer — ML Pipelines",
        "company": "Zeta",
        "location": "Bengaluru, India",
        "source": "Dice",
        "url": "https://www.dice.com/jobs?q=Data+Engineer+ML+Pipelines+India",
        "description": """Build and maintain data pipelines for ML training and inference. Design feature stores, manage data quality, and optimize query performance. Python, Spark, Airflow, and cloud data platform experience required.""",
        "required_skills": ["python", "sql", "gcp", "aws", "docker", "feature engineering",
                            "ci/cd", "model deployment"],
        "industry": "fintech",
    },
    {
        "title": "AI/ML Consultant",
        "company": "McKinsey & Company",
        "location": "Gurugram, India",
        "source": "Dice",
        "url": "https://www.dice.com/jobs?q=AI+ML+Consultant+McKinsey+India",
        "description": """Lead AI transformation engagements for Fortune 500 clients. Design ML strategy, build PoCs, and guide production deployment. MBA/MS preferred with strong Python, cloud, and client presentation skills.""",
        "required_skills": ["python", "machine learning", "gcp", "aws", "communication",
                            "stakeholder", "consulting", "data analysis", "sql"],
        "industry": "consulting",
    },
    # CutShort
    {
        "title": "Data Scientist — Fraud Detection",
        "company": "Paytm",
        "location": "Noida, India",
        "source": "CutShort",
        "url": "https://cutshort.io/jobs?q=Data+Scientist+Fraud+Detection+Paytm",
        "description": """Build real-time fraud detection systems for digital payments. Design anomaly detection models, feature pipelines, and monitoring dashboards. Python, XGBoost, and experience with high-throughput transaction data required.""",
        "required_skills": ["python", "xgboost", "machine learning", "fraud detection",
                            "feature engineering", "pandas", "sql", "risk modeling"],
        "industry": "fintech",
    },
    {
        "title": "LLM Engineer — RAG Systems",
        "company": "HealthifyMe",
        "location": "Bengaluru, India",
        "source": "CutShort",
        "url": "https://cutshort.io/jobs?q=LLM+Engineer+RAG+Bengaluru",
        "description": """Build RAG-based AI coaching systems for personalized health recommendations. Design vector search pipelines, fine-tune LLMs, and build evaluation frameworks. Python, LangChain, and vector database experience required.""",
        "required_skills": ["python", "langchain", "rag", "llm", "fine-tuning", "docker",
                            "nlp", "transformers", "huggingface"],
        "industry": "saas",
    },
    {
        "title": "Data Science Intern",
        "company": "PharmEasy",
        "location": "Mumbai, India",
        "source": "CutShort",
        "url": "https://cutshort.io/jobs?q=Data+Science+Intern+PharmEasy",
        "description": """Internship opportunity in healthcare analytics. Work on demand forecasting, customer segmentation, and supply chain optimization. Python, SQL, and basic ML knowledge required. Mentorship and full-time conversion opportunity available.""",
        "required_skills": ["python", "sql", "pandas", "numpy", "scikit-learn", "data analysis",
                            "forecasting", "machine learning"],
        "industry": "healthcare",
    },
    # Shine
    {
        "title": "Machine Learning Engineer — Search & Discovery",
        "company": "Myntra",
        "location": "Bengaluru, India",
        "source": "Shine",
        "url": "https://www.shine.com/jobsearch?q=Machine+Learning+Engineer+Myntra",
        "description": """Build ML models for fashion search, visual discovery, and personalized recommendations. Work with image data, user behavior sequences, and real-time inference pipelines. PyTorch, TensorFlow, and MLOps experience required.""",
        "required_skills": ["python", "pytorch", "tensorflow", "recommendation system",
                            "deep learning", "docker", "feature engineering", "model deployment"],
        "industry": "ecommerce",
    },
    {
        "title": "Data Scientist — Customer Analytics",
        "company": "HDFC Bank",
        "location": "Mumbai, India",
        "source": "Shine",
        "url": "https://www.shine.com/jobsearch?q=Data+Scientist+HDFC+Bank",
        "description": """Drive customer analytics and ML models for India's largest private bank. Build propensity models, customer lifetime value models, and churn prediction systems. Python, SQL, and experience with financial data required.""",
        "required_skills": ["python", "sql", "machine learning", "predictive modeling",
                            "feature engineering", "pandas", "statistical analysis", "communication"],
        "industry": "fintech",
    },
    {
        "title": "AI Product Analyst",
        "company": "Ola",
        "location": "Bengaluru, India",
        "source": "Shine",
        "url": "https://www.shine.com/jobsearch?q=AI+Product+Analyst+Ola",
        "description": """Analyse AI product performance, user behaviour, and business metrics. Define KPIs for ML features, run experiments, and generate insights to guide product roadmap. SQL, Python, and product analytics experience required.""",
        "required_skills": ["python", "sql", "data analysis", "a/b testing", "data visualization",
                            "pandas", "numpy", "communication", "stakeholder"],
        "industry": "saas",
    },
    # Hirect
    {
        "title": "Junior ML Engineer",
        "company": "Smallcase",
        "location": "Bengaluru, India",
        "source": "Hirect",
        "url": "https://hirec.in/jobs?q=Junior+ML+Engineer+Smallcase",
        "description": """Entry-level ML role at a fintech startup. Build and maintain ML models for portfolio management and financial recommendations. Python, Scikit-learn, and SQL required. Strong mentorship culture with growth opportunities.""",
        "required_skills": ["python", "scikit-learn", "sql", "machine learning", "pandas",
                            "numpy", "data analysis"],
        "industry": "fintech",
    },
    {
        "title": "Data Analyst — Growth",
        "company": "Groww",
        "location": "Bengaluru, India",
        "source": "Hirect",
        "url": "https://hirec.in/jobs?q=Data+Analyst+Growth+Groww",
        "description": """Drive growth analytics for India's fastest-growing investment platform. Analyse user acquisition funnels, retention cohorts, and feature adoption. SQL, Python, and strong business acumen required. Experience with Mixpanel/Amplitude preferred.""",
        "required_skills": ["python", "sql", "data analysis", "data visualization", "a/b testing",
                            "pandas", "numpy", "communication"],
        "industry": "fintech",
    },
    {
        "title": "AI Engineer — Voice AI",
        "company": "Krutrim (AI Startup)",
        "location": "Bengaluru, India",
        "source": "Hirect",
        "url": "https://hirec.in/jobs?q=AI+Engineer+Voice+AI+Bengaluru",
        "description": """Build voice-based AI agents for Indic languages. Work on speech recognition, text-to-speech, and conversational AI systems. Python, deep learning, and NLP experience required. Knowledge of Indic languages is a plus.""",
        "required_skills": ["python", "deep learning", "nlp", "pytorch", "transformers",
                            "huggingface", "fine-tuning", "docker", "gcp"],
        "industry": "saas",
    },
    # Glassdoor (add more)
    {
        "title": "Senior Data Scientist — Marketplace",
        "company": "Urban Company",
        "location": "Gurugram, India",
        "source": "Glassdoor",
        "url": "https://www.glassdoor.co.in/Job/jobs.htm?sc.keyword=Senior+Data+Scientist+Urban+Company",
        "description": """Optimize Urban Company's marketplace using ML. Build pricing models, demand forecasting, and service provider matching algorithms. Python, causal inference, and experimentation experience required.""",
        "required_skills": ["python", "machine learning", "forecasting", "feature engineering",
                            "pandas", "sql", "a/b testing", "deep learning", "statistical analysis"],
        "industry": "saas",
    },
    {
        "title": "Data Scientist — Supply Chain AI",
        "company": "BigBasket",
        "location": "Bengaluru, India",
        "source": "Glassdoor",
        "url": "https://www.glassdoor.co.in/Job/jobs.htm?sc.keyword=Data+Scientist+Supply+Chain+BigBasket",
        "description": """Apply ML to optimize grocery supply chain operations. Build demand forecasting, inventory optimization, and routing models. Python, time series analysis, and optimization experience required.""",
        "required_skills": ["python", "forecasting", "time series", "machine learning", "pandas",
                            "numpy", "sql", "feature engineering", "predictive modeling"],
        "industry": "ecommerce",
    },
    # Naukri.com (add more)
    {
        "title": "Data Science Manager",
        "company": "ICICI Bank",
        "location": "Mumbai, India",
        "source": "Naukri.com",
        "url": "https://www.naukri.com/data-science-manager-jobs?k=data%20science%20manager",
        "description": """Lead a team of data scientists building credit risk and customer analytics models. Manage project delivery, stakeholder communication, and model governance. Python, ML expertise, and team leadership experience required.""",
        "required_skills": ["python", "machine learning", "sql", "risk modeling", "communication",
                            "stakeholder", "feature engineering", "statistical analysis"],
        "industry": "fintech",
    },
    {
        "title": "AI Engineer — Document Processing",
        "company": "Genpact",
        "location": "Gurugram, India",
        "source": "Naukri.com",
        "url": "https://www.naukri.com/ai-engineer-jobs?k=AI%20Engineer%20Document%20Processing",
        "description": """Build AI-powered document processing solutions using OCR, NLP, and LLMs. Design extraction pipelines, train custom models, and deploy to production. Python, OCR, and document AI experience required.""",
        "required_skills": ["python", "nlp", "ocr", "llm", "docker", "gcp",
                            "entity extraction", "transformers", "pandas"],
        "industry": "saas",
    },
    # ZipRecruiter (add more)
    {
        "title": "ML Scientist — Recommendation Systems",
        "company": "TikTok",
        "location": "Bengaluru, India",
        "source": "ZipRecruiter",
        "url": "https://www.ziprecruiter.com/jobs/search?q=ML+Scientist+Recommendation+TikTok+Bengaluru",
        "description": """Build state-of-the-art recommendation algorithms for short-form video content. Work on user embeddings, real-time personalization, and multi-modal models. PyTorch, large-scale ML systems, and strong research background required.""",
        "required_skills": ["python", "pytorch", "recommendation system", "deep learning",
                            "feature engineering", "model evaluation", "nlp", "computer vision"],
        "industry": "saas",
    },
    {
        "title": "Data Analyst — Business Intelligence",
        "company": "Amazon",
        "location": "Bengaluru, India",
        "source": "ZipRecruiter",
        "url": "https://www.ziprecruiter.com/jobs/search?q=Data+Analyst+Amazon+Bengaluru+2025",
        "description": """Analyse Amazon's operations data to drive efficiency improvements. Build dashboards, automate reporting, and partner with operations teams. SQL expertise required, Python and data visualization skills preferred.""",
        "required_skills": ["sql", "python", "data analysis", "data visualization", "pandas",
                            "communication", "stakeholder"],
        "industry": "ecommerce",
    },
    # Indeed (add more)
    {
        "title": "Data Scientist — NLP & Search",
        "company": "MakeMyTrip",
        "location": "Gurugram, India",
        "source": "Indeed",
        "url": "https://www.indeed.co.in/jobs?q=Data+Scientist+NLP+MakeMyTrip",
        "description": """Improve travel search and recommendation using NLP and ML. Build semantic search, hotel recommendation, and travel intent prediction models. Python, NLP, and search relevance experience required.""",
        "required_skills": ["python", "nlp", "machine learning", "recommendation system",
                            "feature engineering", "sql", "pandas", "deep learning"],
        "industry": "saas",
    },
    {
        "title": "AI Research Intern",
        "company": "Samsung R&D",
        "location": "Bengaluru, India",
        "source": "Indeed",
        "url": "https://www.indeed.co.in/jobs?q=AI+Research+Intern+Samsung+Bengaluru",
        "description": """Research and implement novel deep learning methods for on-device AI. Work on model compression, efficient architectures, and edge deployment. Python, PyTorch, and strong fundamentals in deep learning required. Publication track record valued.""",
        "required_skills": ["python", "pytorch", "deep learning", "model optimization",
                            "research", "nlp", "computer vision", "transformers"],
        "industry": "saas",
    },
    {
        "title": "Data Engineer — ML Platform",
        "company": "Zomato",
        "location": "Gurugram, India",
        "source": "Indeed",
        "url": "https://www.indeed.co.in/jobs?q=Data+Engineer+ML+Platform+Zomato",
        "description": """Build Zomato's ML platform — feature store, model registry, and inference infrastructure. Enable data scientists to deploy models faster. Python, Spark, Kafka, and Kubernetes experience required.""",
        "required_skills": ["python", "sql", "docker", "kubernetes", "gcp", "ci/cd",
                            "feature engineering", "model deployment"],
        "industry": "ecommerce",
    },
    # Glassdoor
    {
        "title": "Product Manager — AI",
        "company": "Spotify",
        "location": "Bengaluru, India",
        "source": "Glassdoor",
        "url": "https://www.glassdoor.co.in/Job/product-manager-ai-spotify-jobs",
        "description": """Define product strategy for AI-powered music recommendation features. Work with ML engineers to personalize the listening experience. Strong product sense, data analysis skills, and experience with A/B testing required.""",
        "required_skills": ["data analysis", "a/b testing", "communication", "stakeholder",
                            "agile", "project management", "machine learning"],
        "industry": "media",
    },
    {
        "title": "Data Engineer",
        "company": "Intel",
        "location": "Bengaluru, India",
        "source": "Glassdoor",
        "url": "https://www.glassdoor.co.in/Job/data-engineer-intel-jobs",
        "description": """Build and maintain data pipelines for semiconductor manufacturing analytics. Work with Spark, Kafka, and large-scale time series data. Strong Python, SQL, and data modeling skills required.""",
        "required_skills": ["python", "sql", "spark", "kafka", "docker", "data analysis",
                            "pandas", "ci/cd"],
        "industry": "saas",
    },
    # Wellfound
    {
        "title": "Software Engineer — AI/ML",
        "company": "Krutrim",
        "location": "Bengaluru, India",
        "source": "Wellfound",
        "url": "https://wellfound.com/jobs/search?q=AI+ML+Engineer+Krutrim",
        "description": """Build AI-powered developer tools at an early-stage startup. Work across the stack — from training models to shipping production features. Full-stack capabilities and ML experience highly valued in a fast-paced environment.""",
        "required_skills": ["python", "machine learning", "react", "fastapi", "docker",
                            "git", "nlp", "llm", "agile"],
        "industry": "saas",
    },
    {
        "title": "Backend Engineer — Payments",
        "company": "Cred",
        "location": "Bengaluru, India",
        "source": "Wellfound",
        "url": "https://wellfound.com/jobs/search?q=Backend+Engineer+Cred",
        "description": """Design and build scalable payment processing systems. Architect microservices handling millions of transactions. Strong Python, FastAPI, PostgreSQL, and event-driven architecture experience required.""",
        "required_skills": ["python", "fastapi", "postgresql", "redis", "docker",
                            "microservices", "event-driven", "sql", "git"],
        "industry": "fintech",
    },
    # Google Jobs
    {
        "title": "Solutions Architect — Cloud AI",
        "company": "Google",
        "location": "Bengaluru, India",
        "source": "Google Jobs",
        "url": "https://www.google.com/search?q=Solutions+Architect+Cloud+AI+Google+Bengaluru&ibp=htl;jobs",
        "description": """Design cloud-native AI solutions for enterprise customers. Architect end-to-end ML pipelines on GCP using Vertex AI, BigQuery, and Kubernetes. Google Cloud certifications and customer-facing experience preferred.""",
        "required_skills": ["gcp", "vertex ai", "docker", "kubernetes", "bigquery",
                            "python", "machine learning", "communication"],
        "industry": "saas",
    },
    # Monster
    {
        "title": "Senior ML Engineer",
        "company": "Walmart",
        "location": "Bengaluru, India",
        "source": "Monster",
        "url": "https://www.monsterindia.com/search/senior-ml-engineer-walmart-jobs",
        "description": """Build ML models for supply chain optimization and demand forecasting. Scale ML workflows across Walmart's global retail network. Python, Spark, and production ML experience required.""",
        "required_skills": ["python", "machine learning", "spark", "sql", "docker",
                            "forecasting", "pandas", "feature engineering", "model deployment"],
        "industry": "ecommerce",
    },
    # TimesJobs
    {
        "title": "Data Scientist — Risk Analytics",
        "company": "HDFC Bank",
        "location": "Mumbai, India",
        "source": "TimesJobs",
        "url": "https://www.timesjobs.com/jobsearch/Data-Scientist-Risk-Analytics-HDFC-Bank",
        "description": """Develop credit risk and fraud detection models using ML. Analyze transaction patterns, build risk scoring systems, and ensure model compliance. Strong Python, statistical modeling, and risk analytics background required.""",
        "required_skills": ["python", "machine learning", "sql", "risk modeling",
                            "fraud detection", "statistical analysis", "feature engineering",
                            "pandas"],
        "industry": "fintech",
    },
    # Dice
    {
        "title": "Data Scientist — Logistics",
        "company": "Licious",
        "location": "Bengaluru, India",
        "source": "Dice",
        "url": "https://www.dice.com/jobs?q=Data+Scientist+Licious+Bengaluru",
        "description": """Optimize supply chain and delivery logistics using data science. Build demand forecasting models, route optimization algorithms, and inventory management systems. Python, ML, and operations research background preferred.""",
        "required_skills": ["python", "machine learning", "sql", "forecasting",
                            "data analysis", "pandas", "feature engineering",
                            "statistical analysis"],
        "industry": "ecommerce",
    },
    {
        "title": "AI Engineer — Healthcare NLP",
        "company": "McKinsey & Company",
        "location": "Gurugram, India",
        "source": "Dice",
        "url": "https://www.dice.com/jobs?q=AI+Engineer+Healthcare+McKinsey",
        "description": """Build NLP solutions for healthcare consulting engagements. Extract insights from medical literature, clinical notes, and regulatory documents. Python, NLP, and consulting experience preferred.""",
        "required_skills": ["python", "nlp", "transformers", "llm", "rag",
                            "docker", "gcp", "communication", "healthcare"],
        "industry": "healthcare",
    },
    # CutShort
    {
        "title": "ML Engineer — Recommendation Systems",
        "company": "Paytm",
        "location": "Noida, India",
        "source": "CutShort",
        "url": "https://cutshort.io/jobs/search?q=ML+Engineer+Paytm",
        "description": """Build and optimize recommendation systems for Paytm's fintech platform. Work on user personalization, merchant recommendations, and content ranking. Python, PyTorch, and production ML experience required.""",
        "required_skills": ["python", "pytorch", "recommendation system", "sql",
                            "feature engineering", "a/b testing", "docker", "git"],
        "industry": "fintech",
    },
    {
        "title": "Data Scientist — Health Tech",
        "company": "HealthifyMe",
        "location": "Bengaluru, India",
        "source": "CutShort",
        "url": "https://cutshort.io/jobs/search?q=Data+Scientist+HealthifyMe",
        "description": """Build ML models for personalized health and fitness recommendations. Analyze user behavior data, build predictive models for health outcomes, and work with product teams. Python, ML, and health data experience preferred.""",
        "required_skills": ["python", "machine learning", "sql", "data analysis",
                            "pandas", "feature engineering", "a/b testing", "statistical analysis"],
        "industry": "healthcare",
    },
    # Shine
    {
        "title": "Data Analyst — Marketing Analytics",
        "company": "Myntra",
        "location": "Bengaluru, India",
        "source": "Shine",
        "url": "https://www.shine.com/jobsearch/data-analyst-myntra",
        "description": """Drive marketing ROI analysis and customer segmentation for India's leading fashion platform. Build dashboards, run campaign analysis, and provide actionable insights. SQL, Python, and data visualization skills required.""",
        "required_skills": ["sql", "python", "data analysis", "data visualization",
                            "a/b testing", "pandas", "communication", "stakeholder"],
        "industry": "ecommerce",
    },
    # Hirect
    {
        "title": "Full Stack Data Scientist",
        "company": "Smallcase",
        "location": "Bengaluru, India",
        "source": "Hirect",
        "url": "https://www.hirect.in/jobs/search?q=Full+Stack+Data+Scientist+Smallcase",
        "description": """End-to-end ML ownership at a fintech startup — from data pipelines to model deployment. Build investment recommendation models and real-time portfolio analytics. Python, FastAPI, and production ML experience required.""",
        "required_skills": ["python", "fastapi", "sql", "docker", "machine learning",
                            "feature engineering", "model deployment", "pandas", "ci/cd"],
        "industry": "fintech",
    },
    {
        "title": "Senior Data Scientist",
        "company": "Groww",
        "location": "Bengaluru, India",
        "source": "Hirect",
        "url": "https://www.hirect.in/jobs/search?q=Senior+Data+Scientist+Groww",
        "description": """Lead data science initiatives for India's fastest-growing investment platform. Build risk models, personalize user experience, and drive data-driven product decisions. Python, ML, and fintech experience preferred.""",
        "required_skills": ["python", "machine learning", "sql", "risk modeling",
                            "feature engineering", "a/b testing", "pandas", "leadership"],
        "industry": "fintech",
    },
]

MATCH_CATEGORIES = {
    "python": "Languages",
    "sql": "Languages",
    "machine learning": "ML & AI",
    "deep learning": "ML & AI",
    "nlp": "ML & AI",
    "llm": "ML & AI",
    "rag": "ML & AI",
    "langchain": "ML & AI",
    "huggingface": "ML & AI",
    "transformers": "ML & AI",
    "pytorch": "ML & AI",
    "tensorflow": "ML & AI",
    "scikit-learn": "ML & AI",
    "xgboost": "ML & AI",
    "fine-tuning": "ML & AI",
    "feature engineering": "ML & AI",
    "model evaluation": "ML & AI",
    "data analysis": "Data & Analytics",
    "data visualization": "Data & Analytics",
    "pandas": "Data & Analytics",
    "numpy": "Data & Analytics",
    "statistical analysis": "Data & Analytics",
    "a/b testing": "Data & Analytics",
    "gcp": "Cloud & DevOps",
    "aws": "Cloud & DevOps",
    "docker": "Cloud & DevOps",
    "kubernetes": "Cloud & DevOps",
    "terraform": "Cloud & DevOps",
    "ci/cd": "Cloud & DevOps",
    "vertex ai": "Cloud & DevOps",
    "fastapi": "Frameworks & Tools",
    "flask": "Frameworks & Tools",
    "streamlit": "Frameworks & Tools",
    "postgresql": "Frameworks & Tools",
    "git": "Frameworks & Tools",
    "tableau": "Data & Analytics",
    "spacy": "ML & AI",
    "model optimization": "ML & AI",
    "model deployment": "Cloud & DevOps",
    "reinforcement learning": "ML & AI",
    "recommendation system": "ML & AI",
    "forecasting": "Data & Analytics",
    "fraud detection": "ML & AI",
    "risk modeling": "ML & AI",
    "statistical modeling": "ML & AI",
    "predictive modeling": "ML & AI",
    "time series": "Data & Analytics",
    "text classification": "ML & AI",
    "entity extraction": "ML & AI",
    "computer vision": "ML & AI",
    "ocr": "ML & AI",
    "google adk": "ML & AI",
    "langgraph": "ML & AI",
    "multi-agent": "ML & AI",
    "vertex ai": "Cloud & DevOps",
    "azure": "Cloud & DevOps",
    "research": "Soft Skills",
    "communication": "Soft Skills",
    "stakeholder": "Soft Skills",
    "consulting": "Soft Skills",
    "agent": "ML & AI",
    "generative ai": "ML & AI",
    "prompt engineering": "ML & AI",
    "model monitoring": "Cloud & DevOps",
    "cloud": "Cloud & DevOps",
    "collaborative filtering": "ML & AI",
    "clinical": "Healthcare",
    "healthcare": "Healthcare",
    "entity extraction": "ML & AI",
    "text classification": "ML & AI",
    "ocr": "ML & AI",
    "spacy": "ML & AI",
    "time series": "Data & Analytics",
    "predictive modeling": "ML & AI",
    "statistical modeling": "ML & AI",
    "model optimization": "ML & AI",
    "multi-agent": "ML & AI",
    "risk modeling": "ML & AI",
    "react": "Frameworks & Tools",
    "typescript": "Languages",
    "javascript": "Languages",
    "html": "Frameworks & Tools",
    "css": "Frameworks & Tools",
    "c++": "Languages",
    "c#": "Languages",
    "asp.net": "Frameworks & Tools",
    "r": "Languages",
    "rest api": "Frameworks & Tools",
    "agile": "Soft Skills",
    "leadership": "Soft Skills",
    "project management": "Soft Skills",
    "microservices": "Cloud & DevOps",
    "event-driven": "Cloud & DevOps",
    "kafka": "Data & Analytics",
    "spark": "Data & Analytics",
    "bigquery": "Data & Analytics",
    "redis": "Frameworks & Tools",
    "plotly": "Data & Analytics",
    "performance optimization": "ML & AI",
    "webpack": "Frameworks & Tools",
    "logistic regression": "ML & AI",
    "mlops": "Cloud & DevOps",
    "optimization": "ML & AI",
    "document processing": "ML & AI",
}


def compute_job_match(profile_text: str, job: dict) -> dict:
    text_lower = profile_text.lower()
    required = job.get("required_skills", [])
    matched_skills = []
    missing_skills = []

    for skill in required:
        if skill in text_lower:
            matched_skills.append(skill)
        else:
            missing_skills.append(skill)

    match_pct = round(len(matched_skills) / len(required) * 100, 1) if required else 0

    category_matches = {}
    for skill in matched_skills:
        cat = MATCH_CATEGORIES.get(skill, "Other")
        category_matches[cat] = category_matches.get(cat, 0) + 1

    return {
        "job": job,
        "match_pct": match_pct,
        "matched_skills": matched_skills,
        "missing_skills": missing_skills,
        "total_required": len(required),
        "matched_count": len(matched_skills),
        "category_breakdown": category_matches,
    }


def recommend_jobs(profile_text: str, min_match: int = 20, top_n: int = 10) -> list:
    scored = []
    for job in SAMPLE_JOBS:
        result = compute_job_match(profile_text, job)
        if result["match_pct"] >= min_match:
            scored.append(result)

    scored.sort(key=lambda x: -x["match_pct"])
    return scored[:top_n]
